version: '2.1'
orbs:
  coveralls: coveralls/coveralls@2.1.0
  jobs:
    unit-tests:
      docker:
        - image: cimg/python:3.11.0
          steps:
            - checkout
        - run:
            command: python3 -m venv venv/
            name: Create Python Virtual Environment
        - run:
            command: . venv/bin/activate
            name: Activate Python Virtual Environment
        - run:
            command: python3 -m pip install --upgrade -r requirements.txt
            name: Install Python Dependencies
        - run:
            command: pytest
            name: Run Unit Testing
        - coveralls/upload
workflows: null
