version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.1.0

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          name: Create Python Virtual Environment
          command: python3 -m venv venv/
      - run:
          name: Activate Python Virtual Environment
          command: . venv/bin/activate
      - run:
          name: Install Python Dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
      - run:
          name: Run Unit Testing
          command: python3 -m pytest --cov
      - coveralls/upload

workflows:
  unit-tests-workflow:
    jobs:
      - unit-tests
